name: CD

on:
    push:
        branches:
            - master
            - next

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 15
            - run: npm ci
            - run: npm run lint
            - run: npx semantic-release
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
