name: CI

on:
    push:
        branches:
            - main
            - next
    pull_request:
        branches:
            - main
            - next

jobs:
    testing:
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                node: [14.x, 15.x, 16.x]
                os: [macos-latest, ubuntu-latest, windows-latest]

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node }}
            - run: npm i npm@latest
            - run: npm install-test
